### ISSUE TITLE
Scheduled wheel building not working

### ISSUE THREAD

**Issue by riddell-stan** [stan-dev/httpstan-wheels#68]
The `BUILD_COMMIT` variable is not being set, see https://github.com/stan-dev/httpstan-wheels/runs/1560819086?check_suite_focus=true.

**Comment by ahartikainen** [comment]
I think this should fix the problem: `git fetch --tags`

    echo "BUILD_COMMIT=$(cd httpstan && git fetch --tags && git tag --sort version:refname | tail -1)" >> $GITHUB_ENV

**Comment by riddell-stan** [comment]
Interesting. Do you know why it would work without `git fetch --tags` on 
pull requests and on pushes but not in this `scheduled` run?

**Comment by ahartikainen** [comment]
I have no idea. It will also fails with forks.

I think some default settings change depending how CI is triggered.

**Comment by riddell-stan** [comment]
I think https://github.com/actions/checkout/issues/217 explains what is going on.

I'm reopening this issue because the current solution involves a subshell doing a ton of work. I think we should have a step where we fetch the tags separately, akin to this, perhaps, https://github.com/actions/checkout/issues/217#issuecomment-636481619

**Comment by riddell-stan** [comment]
``git fetch --tags`` will, as I understand it, fetch the entire history. Is that what we want?

```
--tags

Fetch all tags from the remote (i.e., fetch remote tags refs/tags/*
           into local tags with the same name), in addition to whatever else
           would otherwise be fetched. 
```

**Comment by ahartikainen** [comment]
I liked the PR solution. It does add more work for the engine, but I think it is fine.
